// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/users/admin/users_admin.proto

// CAMBIO 1: Diferenciar el paquete de protobuf

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	users "mini-marketplace/proto/users"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_admin_users_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CAMBIO 2: Referenciar "User" usando el paquete "users" del import
	User          *users.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_admin_users_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResponse) GetUser() *users.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_admin_users_admin_proto_rawDescGZIP(), []int{2}
}

type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CAMBIO 2: Igual aquí
	Users         []*users.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_admin_users_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_admin_users_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*users.User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_users_admin_users_admin_proto protoreflect.FileDescriptor

const file_proto_users_admin_users_admin_proto_rawDesc = "" +
	"\n" +
	"#proto/users/admin/users_admin.proto\x12\vusers.admin\x1a\x17proto/users/users.proto\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x0fGetUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"\x12\n" +
	"\x10ListUsersRequest\"6\n" +
	"\x11ListUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users2\xa5\x01\n" +
	"\x11UsersAdminService\x12J\n" +
	"\tListUsers\x12\x1d.users.admin.ListUsersRequest\x1a\x1e.users.admin.ListUsersResponse\x12D\n" +
	"\aGetUser\x12\x1b.users.admin.GetUserRequest\x1a\x1c.users.admin.GetUserResponseB$Z\"mini-marketplace/proto/users/adminb\x06proto3"

var (
	file_proto_users_admin_users_admin_proto_rawDescOnce sync.Once
	file_proto_users_admin_users_admin_proto_rawDescData []byte
)

func file_proto_users_admin_users_admin_proto_rawDescGZIP() []byte {
	file_proto_users_admin_users_admin_proto_rawDescOnce.Do(func() {
		file_proto_users_admin_users_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_users_admin_users_admin_proto_rawDesc), len(file_proto_users_admin_users_admin_proto_rawDesc)))
	})
	return file_proto_users_admin_users_admin_proto_rawDescData
}

var file_proto_users_admin_users_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_users_admin_users_admin_proto_goTypes = []any{
	(*GetUserRequest)(nil),    // 0: users.admin.GetUserRequest
	(*GetUserResponse)(nil),   // 1: users.admin.GetUserResponse
	(*ListUsersRequest)(nil),  // 2: users.admin.ListUsersRequest
	(*ListUsersResponse)(nil), // 3: users.admin.ListUsersResponse
	(*users.User)(nil),        // 4: users.User
}
var file_proto_users_admin_users_admin_proto_depIdxs = []int32{
	4, // 0: users.admin.GetUserResponse.user:type_name -> users.User
	4, // 1: users.admin.ListUsersResponse.users:type_name -> users.User
	2, // 2: users.admin.UsersAdminService.ListUsers:input_type -> users.admin.ListUsersRequest
	0, // 3: users.admin.UsersAdminService.GetUser:input_type -> users.admin.GetUserRequest
	3, // 4: users.admin.UsersAdminService.ListUsers:output_type -> users.admin.ListUsersResponse
	1, // 5: users.admin.UsersAdminService.GetUser:output_type -> users.admin.GetUserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_users_admin_users_admin_proto_init() }
func file_proto_users_admin_users_admin_proto_init() {
	if File_proto_users_admin_users_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_users_admin_users_admin_proto_rawDesc), len(file_proto_users_admin_users_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_users_admin_users_admin_proto_goTypes,
		DependencyIndexes: file_proto_users_admin_users_admin_proto_depIdxs,
		MessageInfos:      file_proto_users_admin_users_admin_proto_msgTypes,
	}.Build()
	File_proto_users_admin_users_admin_proto = out.File
	file_proto_users_admin_users_admin_proto_goTypes = nil
	file_proto_users_admin_users_admin_proto_depIdxs = nil
}
